version: "3"

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:helneff
    container_name: nginx
    env_file: .env
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:helneff
    container_name: mariadb
    env_file: .env
    restart: always
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:helneff
    container_name: wordpress
    env_file: .env
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/helneff/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/helneff/data/wordpress
      o: bind

networks:
  inception:
